# "$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
[‚ñë‚ñí‚ñì](#a3aed2)\
[ Û∞£á ](bg:#a3aed2 fg:#090c0c)\
[ÓÇ¥](bg:#769ff0 fg:#a3aed2)\
$directory\
[ÓÇ¥](fg:#769ff0 bg:#394260)\
$git_branch$git_commit$git_state\
$git_status\
[ÓÇ¥](fg:#394260 bg:#212736)\
$azure\
$golang\
$helm\
$kubernetes\
$lua\
$nodejs\
$python\
$terraform\
[ÓÇ¥](fg:#212736 bg:#1d2230)\
$time\
$battery\
[ÓÇ¥](fg:#1d2230)\
\n$character"""

right_format = """
$aws\
$buf\
$c\
$cmake\
$cobol\
$conda\
$cpp\
$crystal\
$custom\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gcloud\
$gradle\
$guix_shell\
$haskell\
$haxe\
$helm\
$hg_branch\
$julia\
$kotlin\
$memory_usage\
$meson\
$nim\
$ocaml\
$opa\
$openstack\
$os\
$perl\
$php\
$pijul_channel\
$pixi\
$pulumi\
$purescript\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$singularity\
$solidity\
$spack\
$status\
$swift\
$vagrant\
$vcsh\
$vlang\
$zig\
"""

continuation_prompt = '‚ñ∂‚ñ∂ '

# style_choices:
# bold
# italic
# underline
# dimmed
# inverted
# blink
# hidden
# strikethrough
# bg:<color>
# fg:<color>
# <color>
# none

#NOTE: you can customize the symbols, e.g:
# [character]
# success_symbol = "[ ÓòÇ ]($bold fg:#f8f8f2)"
# error_symbol   = "[ ‚û§ ]($bold fg:#fb4934)"

[directory]
style             = "fg:#e3e5e5 bg:#769ff0"
format            = "[ $path ](bold $style)"
home_symbol       = '~'
read_only         = ' ÔÄ£ '
truncation_length = 3
truncation_symbol = "‚Ä¶/"

[directory.substitutions]
"Documents" = "Û∞àô "
"Downloads" = "ÔÄô "
"Music"     = "ÔÄÅ "
"Pictures"  = "ÔÄæ "

[git_branch]
symbol = "Ôêò"
style  = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style      = "bg:#394260"
conflicted = 'üè≥'
up_to_date = ''
untracked  = 'Ôî© '
ahead      = '‚á°${count}'
diverged   = '‚áï‚á°${ahead_count}‚á£${behind_count}'
behind     = '‚á£${count}'
stashed    = 'Ô£ñ '
modified   = 'ÔÅÑ '
staged     = '[++\($count\)](green)'
renamed    = 'Ë•Å '
deleted    = 'ÔÄî '
format     = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[time]
disabled    = false
time_format = "%R" # Hour:Minute Format
style       = "bg:#1d2230"
format      = '[[ Ôê∫ $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[battery]
full_symbol        = "Û∞Åπ"
charging_symbol    = "Ó¨≠"
discharging_symbol = "Û±êã"
format             = '[ $symbol $percentage](fg:#a0a9cb bg:#1d2230)'

# battery warning
[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[[battery.display]]
threshold = 50
style = "bold green"

[deno]
symbol         = "Ó¥ç"
version_format = "${raw}"
format         = " [deno](italic) [${symbol}](green bold)"

[lua]
symbol         = "‚®Ä"
style          = "bold bright-yellow"
version_format = "${raw}"
format         = " [lua](italic) [${symbol}]($style) "

[nodejs]
symbol            = "Óúò"
style             = "fg:#39ff14"
detect_extensions = []
detect_folders    = ["node_modules"]
detect_files      = ["package-lock.json", "yarn.lock"]
version_format    = "v${major}.${minor}"
format            = '[ [${symbol}]($style) ($version)](fg:#769ff0 bg:#212736)'

[python]
symbol            = "Óúº"
style             = "fg:#39ff14"
version_format    = "v${major}.${minor}"
format            = '[ [${symbol}]($style) (${virtualenv}) ${version} ](fg:#769ff0 bg:#212736)'

[ruby]
symbol            = "ÓòÖ"
style             = "bold red"
version_format    = "${raw}"
format            = " [rb](italic) [${symbol}]($style) "

[rust]
symbol = "Óû®"
style  = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[swift]
symbol         = "Óöô"
style          = "bold bright-red"
version_format = "${raw}"
format         = " [sw](italic) [${symbol}]($style)"

[aws]
symbol   = "ÔÉØ"
style    = "bold blue"
disabled = true
format   = " [aws](italic) [$symbol $profile $region]($style)"

[buf]
symbol = "‚ñ†"
style  = "bold bright-red"
format = " [buf](italic) [$symbol $buf_version]($style)"

[c]
symbol = "‚ÑÇ"
style  = "bold bright-cyan"
format = " [$symbol(-$name)]($style) "

[cpp]
symbol = " "
style  = "bold bright-cyan"
format = " [cpp](italic) [$symbol]($style)"

[kotlin]
symbol = " "
style  = "bold bright-red"
format = " [kotlin](italic) [$symbol]($style)"

[ocaml]
symbol = " "
style  = "bold bright-yellow"
format = " [ocaml](italic) [$symbol]($style)"

[perl]
symbol = "Óôæ"
style  = "bold bright-cyan"
format = " [perl](italic) [$symbol]($style) "

[php]
symbol = "Óòà"
style  = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[pixi]
symbol = "pixi "
style = "bold bright-yellow"
format = " [pixi](italic) [$symbol]($style)"

[rlang]
symbol = " "
style = "bold bright-cyan"
format = " [rlang](italic) [$symbol]($style)"

[meson]
symbol = "meson "
style  = "bold bright-red"
format = " [meson](italic) [$symbol]($style)"

[conda]
symbol = "‚óØ"
style  = "bold bright-red"
format = " conda [$symbol $environment]($style)"

[dart]
symbol = "Óôå"
style  = "bold bright-cyan"
format = " dart [$symbol]($style) "

[elixir]
symbol = "Óôì"
style  = "bold bright-yellow"
format = " exs [$symbol OTP $otp_version ]($style)"

[elm]
symbol = "‚ó©"
style  = "bold bright-red"
format = " elm [$symbol]($style) "

[golang]
symbol = "Óòß"
style  = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[haskell]
symbol = "‚ùØŒª"
style  = "bold bright-yellow"
format = " hs [$symbol]($style) "

[java]
symbol = "Óú∏"
style  = "bold bright-red"
format = " java [${symbol}]($style) "

[julia]
symbol = "‚óé"
style  = "bold bright-cyan"
format = " jl [$symbol]($style) "

[memory_usage]
symbol = "‚ñ™‚ñ´‚ñ™"
style  = "bold bright-cyan"
format = " mem [${ram}( ${swap})]($style)"

[nim]
symbol = "‚ñ¥‚ñ≤‚ñ¥"
style  = "bold bright-yellow"
format = " nim [$symbol]($style) "

[nix_shell]
symbol      = 'Ôåì'
style       = 'bold italic dimmed blue'
impure_msg  = '[‚åΩ](bold dimmed red)'
pure_msg    = '[‚åæ](bold dimmed green)'
unknown_msg = '[‚óå](bold dimmed ellow)'
format      = '[$symbol nix‚é™$state‚é™]($style) [$name](italic dimmed white)'

[spack]
symbol = "‚óá"
style  = "bold bright-yellow"
format = " spack [$symbol$environment]($style) "

[zig]
symbol = "Óö©"
style  = "bold bright-yellow"
format = " zig [$symbol]($style) "

[scala]
symbol = "Óöé"
format = " scala [$symbol]($style) "

[singularity]
symbol = "singularity "
style  = "bold bright-yellow"
format = " [singularity](italic) [$symbol]($style)"

[kubernetes]
symbol = "Ó†ù"
style  = "bold bright-cyan"
format = " [kubernetes](italic) [$symbol]($style) "

[helm]
symbol       ="‚õµ"
detect_files = ['helm-release.yaml']
format       = "[$symbol $version](bold white) "
disabled     = false

[vcsh]
symbol = "vcsh "
style  = "bold bright-red"
format = " [vcsh](italic) [$symbol]($style)"

[cobol]
symbol = "cobol "
style  = "bold bright-yellow"
format = " [cobol](italic) [$symbol]($style)"

[daml]
symbol = "daml "
style  = "bold bright-cyan"
format = " [daml](italic) [$symbol]($style)"

[dotnet]
symbol = ".NET "
style  = "bold bright-red"
format = " [dotnet](italic) [$symbol]($style)"

[erlang]
symbol = "Ôàø"
style  = "bold bright-yellow"
format = " [erlang](italic) [$symbol]($style) "

[fennel]
style = "bold bright-cyan"
format = " [fennel](italic) [$symbol]($style)"
symbol = "ÓöØ "

[haxe]
style  = "bold bright-red"
format = " [haxe](italic) [$symbol]($style)"
symbol = "Óô¶ "

[opa]
style = "bold bright-cyan"
format = " [opa](italic) [$symbol]($style)"
symbol = "opa "

[pulumi]
format = " [pulumi](italic) [$symbol]($style)"
style = "bold bright-red"
symbol = "pulumi "

[purescript]
symbol = "Óò∞"
style  = "bold bright-yellow"
format = " [purescript](italic) [$symbol]($style) "

[raku]
symbol = "raku "
style  = "bold bright-cyan"
format = " [raku](italic) [$symbol]($style)"

[red]
symbol = "red "
style  = "bold bright-red"
format = " [red](italic) [$symbol]($style)"

[solidity]
symbol = "Óµò"
style  = "bold bright-yellow"
format = " [solidity](italic) [$symbol]($style) "

[terraform]
symbol = "Ó¢Ω"
style  = "fg:#39ff14"
format = '[ [${symbol}]($style) ($version)](fg:#769ff0 bg:#212736)'

[vlang]
symbol = "vlang "
style  = "bold bright-red"
format = " [vlang](italic) [$symbol]($style)"

[vagrant]
symbol = "vagrant "
style  = "bold bright-yellow"
format = " [vagrant](italic) [$symbol]($style)"

[gcloud]
symbol = "gcloud "
style  = "bold bright-cyan"
format = " [gcloud](italic) [$symbol]($style)"

[openstack]
symbol = "openstack "
style  = "bold bright-red"
format = " [openstack](italic) [$symbol]($style)"

[azure]
symbol = "ÓØò"
style  = "bold bright-blue"
format = " [azure](italic) [$symbol]($style) "

[crystal]
symbol = "Óôá"
style  = "bold bright-cyan"
format = " [crystal](italic) [$symbol]($style) "
